version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - ./temp:/app/temp
    env_file:
      - .env
    depends_on:
      - ai_detection
    networks:
      - smart-assess-network
    restart: on-failure
    environment:
      - PYTHONUNBUFFERED=1

  ai_detection:
    build:
      context: .
      dockerfile: Dockerfile.ai_detection
    ports:
      - "5000:5000"
    networks:
      - smart-assess-network
    restart: on-failure
    volumes:
      - model-cache:/app/models_cache
    environment:
      - PYTHONUNBUFFERED=1

networks:
  smart-assess-network:
    driver: bridge

volumes:
  model-cache: